name: Copy Excel File to Repo B

on:
  push:
    paths:
      # - 'Broker_Analysis.xlsx'
      - '**'
    branches:
      - main
  workflow_dispatch:


jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Clone Repo B
        run: |
          git clone https://x-access-token:${{ secrets.REPO_B_PAT }}@github.com/Ayushbct/testing-for-nepse.git repo-b
          # git clone https://x-access-token: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@github.com/Ayushbct/testing-for-nepse.git repo-b

      - name: Copy Excel file to Repo B
        run: |
          cp Broker_Analysis.xlsx repo-b/

      - name: Commit and push to Repo B
        run: |
          cd repo-b
          git pull origin main
          git add Broker_Analysis.xlsx
          git commit -m "🔄 Update Broker_Analysis.xlsx from Repo A" || echo "No changes to commit"
          git push
