name: Sync Excel to Repo B

on:
  workflow_run:
    workflows: ["Update broker_analysis.xlsx file"]
    types:
      - completed
  push:
    paths:
      - "Broker_Analysis.xlsx"
  workflow_dispatch:

jobs:
  sync:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Clone Repo B
        run: |
          git clone https://x-access-token:${{ secrets.REPO_B_PAT }}@github.com/Ayushbct/testing-for-nepse.git repo-b

      - name: Copy Excel file to Repo B
        run: |
          cp Broker_Analysis.xlsx repo-b/

      - name: Commit and push to Repo B
        run: |
          cd repo-b
          git pull --ff-only origin main
          git add Broker_Analysis.xlsx
          git commit -m "🔄 Sync Broker_Analysis.xlsx from Repo A [automated]" || echo "No changes to commit"
          git push origin main
