name: Copy Excel File to Repo B

on:
  push:
    paths:
      - 'Broker_Analysis.xlsx'
    branches:
      - main

permissions:
  contents: read

jobs:
  copy-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo (Repo A)
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Clone Repo B
        run: |
          git clone https://<your-token>@github.com/<user-or-org>/repo-b.git repo-b
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_B_TOKEN }}

      - name: Copy Excel file to Repo B
        run: |
          cp Broker_Analysis.xlsx repo-b/

      - name: Commit and push to Repo B
        run: |
          cd repo-b
          git add Broker_Analysis.xlsx
          git commit -m "Update Excel file from Repo A"
          git push
