name: Update broker_analysis.xlsx file

on:
  schedule:
    - cron: '45 10 * * 0-5'  # 10:45 AM UTC Sunday to Friday (4:30 PM NPT)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Run broker_nepse_alpha.js
        run: node broker_nepse_alpha.js

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Commit and push changes
        run: |
          # Check if Broker_Analysis.xlsx changed in the working tree or staged area
          if git diff --quiet HEAD -- Broker_Analysis.xlsx; then
            echo "Broker_Analysis.xlsx has NOT changed. Skipping commit."
          else
            echo "Broker_Analysis.xlsx changed. Committing all changes."
            git add -A
            git commit -m "📝 Update files including Broker_Analysis.xlsx [automated]"
            git push origin HEAD:main
          fi
      
